"""Chronological backtest and model-evaluation runner.

A backtest may settle PnL only when a timestamped, verified historical quote
exists at the simulated decision time.  A game with a result but no quote is
an ``EVAL`` prediction; it never receives a placeholder price, stake, ROI or
PnL.  An unfinished game is ``PROPOSED`` or ``OPEN`` and cannot be settled.
"""
from __future__ import annotations

import math
import uuid
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from .. import db
from ..config import FEAT, MAX_STAKE_PCT, STARTING_BANKROLL, am_to_prob
from ..engine.catalog import register_catalog
from ..engine.evaluation import american_pnl
from ..features.engine import compute_features, load_events, load_games
from .ledger import kelly_stake
from .strategies import MODELS, Strategy, build_catalog, special_rules

ROUNDS = ("WC", "DS", "LCS", "WS")


def _update_online_coefs(g, f: dict[str, Any], ctx: dict[str, Any], is_post: bool) -> None:
    """SGD step for the online model coefficients after a completed game.

    Called only AFTER every strategy has already made its decision for this
    game, so coefficients always reflect strictly earlier information.
    """
    from .strategies import _logit, _num, _online_update, _sig
    p_elo = f.get("p_elo")
    if not _num(p_elo):
        return
    home_won = int(g.home_score > g.away_score)
    env = "POST" if is_post else "REG"
    store = ctx.setdefault("online_coefs", {})
    # Bullpen workload coefficient
    bh, ba = f.get("h_bp_bf_l3"), f.get("a_bp_bf_l3")
    if _num(bh) and _num(ba):
        x = (float(ba) - float(bh)) / 10.0
        w = store.setdefault(f"bp_{env}", {"w": 0.0, "n": 0})["w"]
        p_home = _sig(_logit(float(p_elo)) + w * x)
        _online_update(ctx, f"bp_{env}", x, p_home, home_won)
    # Rest-differential coefficient
    rh, ra = f.get("rest_home"), f.get("rest_away")
    if _num(rh) and _num(ra):
        x = max(min(float(rh) - float(ra), 4.0), -4.0)
        w = store.setdefault(f"rest_{env}", {"w": 0.0, "n": 0})["w"]
        p_home = _sig(_logit(float(p_elo)) + w * x)
        _online_update(ctx, f"rest_{env}", x, p_home, home_won)
    # Market-movement coefficient (verified open/close pairs only)
    if f.get("market_quote_verified"):
        from ..config import am_to_prob, devig_two
        h_open, _ = devig_two(am_to_prob(f.get("home_odds")), am_to_prob(f.get("away_odds")))
        h_close, _ = devig_two(am_to_prob(f.get("market_close_home_odds")),
                               am_to_prob(f.get("market_close_away_odds")))
        if _num(h_open) and _num(h_close):
            x = 4.0 * (float(h_close) - float(h_open))
            w = store.setdefault(f"mv_{env}", {"w": 0.0, "n": 0})["w"]
            p_home = _sig(_logit(float(h_close)) + w * x)
            _online_update(ctx, f"mv_{env}", x, p_home, home_won)


def _need(year: int, round_code: str) -> int:
    """Wins required by the historical format, used by series-state tests."""
    from ..config import round_needed
    return round_needed(round_code, int(year))


def _american_to_decimal(odds: float) -> float:
    from ..config import american_to_decimal
    return american_to_decimal(odds)


def _has_score(row) -> bool:
    return bool(getattr(row, "completed", False)) and pd.notna(getattr(row, "home_score", np.nan)) and pd.notna(getattr(row, "away_score", np.nan))


def build_backtest_games() -> pd.DataFrame:
    """Load only source-backed games; fail rather than reconstructing missing rows."""
    games_path = FEAT / "games.parquet"
    if not games_path.exists():
        raise FileNotFoundError(
            f"{games_path} is missing. Fetch and validate a source before running a backtest; "
            "no games are generated by MLBComp."
        )
    games = load_games().copy()
    games["score_available"] = games.apply(_has_score, axis=1)
    # Older builds stored postseason separately.  It is accepted only as a
    # source-backed corpus with a real game_pk, not as a hand-written result.
    if games.round_code.isna().all() and (FEAT / "po_corpus.parquet").exists():
        po = pd.read_parquet(FEAT / "po_corpus.parquet")
        po["game_type"] = "PO"
        po["status"] = np.where(po["score_available"], "F", "PRE")
        po["completed"] = po["score_available"].astype(bool)
        for column in games.columns:
            if column not in po.columns:
                po[column] = np.nan
        games = pd.concat([games, po[games.columns]], ignore_index=True)
    if "start_ts" not in games:
        games["start_ts"] = pd.to_datetime(games["start_utc"], utc=True, errors="coerce")
    games["start_ts"] = pd.to_datetime(games["start_ts"], utc=True, errors="coerce")
    missing_time = games["start_ts"].isna()
    # Calendar date is sufficient for deterministic ordering, but it is not
    # presented as an availability timestamp anywhere in the ledger.
    games.loc[missing_time, "start_ts"] = pd.to_datetime(games.loc[missing_time, "game_date"], utc=True, errors="coerce")
    return games.sort_values(["start_ts", "game_pk"], kind="mergesort").reset_index(drop=True)


def _round_state(g, ctx: dict[str, Any], f: dict[str, Any], is_post: bool) -> dict[str, Any] | None:
    if not is_post or not isinstance(getattr(g, "series_key", None), str):
        f.setdefault("n_series_games_before", 0)
        return None
    key = g.series_key
    if key not in ctx["series"]:
        ctx["series"][key] = {"n": 0, "a": int(g.home_team_id), "b": int(g.away_team_id),
                               "wa": 0, "wb": 0, "year": int(g.season), "round": g.round_code}
    state = ctx["series"][key]
    f["n_series_games_before"] = state["n"]
    f["wins_a_before"] = state["wa"]
    f["wins_b_before"] = state["wb"]
    needed = _need(state["year"], state["round"])
    f["clinch_a"] = int(state["wa"] == needed - 1)
    f["clinch_b"] = int(state["wb"] == needed - 1)
    f["elimination_a"] = int(state["wb"] == needed - 1)
    f["elimination_b"] = int(state["wa"] == needed - 1)
    ctx["series_team_a"] = state["a"]
    return state


def _update_series(g, state: dict[str, Any] | None) -> None:
    if state is None or not _has_score(g):
        return
    home_win = int(g.home_score > g.away_score)
    if int(g.home_team_id) == state["a"]:
        state["wa"] += home_win
        state["wb"] += 1 - home_win
    else:
        state["wb"] += 1 - home_win
        state["wa"] += home_win
    state["n"] += 1


def _outcome(g, decision: dict[str, Any], market: str) -> str | None:
    if not _has_score(g):
        return None
    if market in {"ML", "F5_ML"}:
        home_win = int(g.home_score > g.away_score)
        selected_home = decision["selection"] == "HOME"
        return "W" if ((home_win == 1) == selected_home) else "L"
    if market in {"TOTAL", "F5_TOTAL", "TEAM_TOTAL"}:
        # A model hypothesis line is not a historical market line.  Only a
        # source-backed observed line may generate a scored market outcome.
        if decision.get("observed_line") is None:
            return None
        line = float(decision["observed_line"])
        total = int(g.home_score) + int(g.away_score)
        if total == line:
            return "P"
        over = total > line
        return "W" if ((decision["selection"].startswith("OVER")) == over) else "L"
    return None


def _market_quote(f: dict[str, Any], decision: dict[str, Any], g,
                  verified_source_ids: set[str] | None = None,
                  verified_observation_ids: set[str] | None = None) -> dict[str, Any] | None:
    """Return a quote only with timestamp, explicit verification and source evidence."""
    tier = decision.get("price_tier") or "open"
    side = "home" if decision["selection"] == "HOME" else "away"
    if decision["market"] in {"ML", "F5_ML"}:
        if tier == "close":
            odds = f.get(f"market_close_{side}_odds")
        else:
            odds = f.get(f"{side}_odds")
    else:
        # Totals/run-line rows carry a single juice column, not a two-way
        # quote, so they never produce a wager from this gate.
        odds = f.get("market_odds")
    verified = f.get("market_quote_verified", False)
    observed_at = f.get("market_close_observed_at") if tier == "close" else f.get("market_quote_observed_at")
    available_at = f.get("market_quote_available_at")
    if tier == "close" and verified and not observed_at:
        observed_at = f.get("market_quote_available_at")
    source_id = f.get("market_quote_source_id")
    source_observation_id = f.get("market_quote_source_observation_id")
    if tier == "close" and verified and source_observation_id:
        source_observation_id = str(source_observation_id).replace(":open:", ":close:")
    if verified_observation_ids is not None and source_observation_id:
        if source_observation_id not in verified_observation_ids:
            return None
    elif verified_source_ids is not None and source_id not in verified_source_ids:
        return None
    if not verified or not source_id or not pd.notna(odds) or not observed_at or not available_at:
        return None
    try:
        observed = pd.to_datetime(observed_at, utc=True)
        available = pd.to_datetime(available_at, utc=True)
        start = pd.to_datetime(getattr(g, "start_ts"), utc=True)
        if (pd.isna(observed) or pd.isna(available) or pd.isna(start)
                or observed > start or available > start):
            return None
    except (TypeError, ValueError):
        return None
    return {"american": float(odds), "observed_at": str(observed_at),
            "available_at": f.get("market_quote_available_at"),
            "closing": tier == "close",
            "tier": tier,
            "source_id": f.get("market_quote_source_id"),
            "source_url": f.get("market_quote_source_url"),
            "source_observation_id": source_observation_id,
            "close_american": (f.get("market_close_home_odds") if decision["selection"] == "HOME"
                               else f.get("market_close_away_odds"))}


def _prediction_id(run_id: str, strategy: Strategy, game_pk: int) -> str:
    return f"{run_id}:{strategy.sid}:{game_pk}"


def run_backtest(po_valid_pks: set[int] | None = None, min_season: int = 2015,
                 run_id: str | None = None) -> dict[str, Any]:
    """Run a chronological competition and append a new immutable run."""
    db.init_db()
    run_id = run_id or f"backtest:{uuid.uuid4().hex[:12]}"
    games = build_backtest_games()
    events_path = FEAT / "game_events.parquet"
    odds_path = FEAT / "odds.parquet"
    if not events_path.exists():
        raise FileNotFoundError(f"{events_path} missing; cannot derive point-in-time features")
    events = load_events()
    odds = pd.read_parquet(odds_path) if odds_path.exists() else pd.DataFrame()
    state_df = db.query_df("SELECT * FROM series_state")
    features = compute_features(games, events, state_df, odds)
    verified_observations = db.query_df(
        "SELECT observation_id,source_id FROM source_observations WHERE verification_status='VERIFIED'"
    )
    observation_ids = verified_observations.observation_id.tolist()
    verified_source_ids = set(verified_observations.source_id.tolist())
    verified_observation_ids = set(verified_observations.observation_id.tolist())
    source_observations = db.jdump(observation_ids)
    strategies = register_catalog(build_catalog())
    # Only implemented/data-ready strategies enter the run.  Unsupported
    # hypotheses remain in the catalog and are explicitly visible as such.
    runnable = [s for s in strategies if s.status not in {"DATA_UNAVAILABLE", "REJECTED"}
                and s.model in MODELS]
    db_time = db.utcnow()
    with db.db() as conn:
        conn.execute(
            "INSERT OR IGNORE INTO backtest_runs (run_id,run_type,started_at,data_cutoff,config_json,status,notes) "
            "VALUES (?,?,?,?,?,?,?)",
            (run_id, "BACKTEST", db_time, str(games.start_ts.max()),
             db.jdump({"min_season": min_season, "strategy_count": len(runnable),
                       "price_gate": "verified quote with availability <= decision time"}),
             "RUNNING", "No synthetic prices or fills"),
        )

    ctx: dict[str, Any] = {"series": {}, "series_team_a": None,
                           "round_intercepts": {r: 0.0 for r in ROUNDS},
                           "round_diffs": {r: [] for r in ROUNDS}, "fav_max": -150.0}
    bankrolls = {(s.sid, s.env): STARTING_BANKROLL for s in runnable}
    balances = {(s.sid, s.env): [(None, STARTING_BANKROLL)] for s in runnable}
    metrics: dict[tuple[str, str], list[tuple[float, int]]] = {(s.sid, s.env): [] for s in runnable}
    bets: list[dict[str, Any]] = []
    predictions: list[dict[str, Any]] = []
    counts = {"settled": 0, "eval": 0, "proposed": 0, "open": 0, "skipped": 0}
    last_post_season = None

    for g in games.itertuples(index=False):
        if int(g.season) < min_season:
            continue
        is_post = pd.notna(getattr(g, "round_code", np.nan))
        if is_post and g.season != last_post_season:
            if last_post_season is not None:
                for round_code, residuals in ctx["round_diffs"].items():
                    # Prior seasons only; if sample is too small the intercept
                    # remains zero and the experiment is marked uncertain.
                    if len(residuals) >= 15:
                        ctx["round_intercepts"][round_code] = float(np.clip(np.mean(residuals), -0.25, 0.25))
                    ctx["round_diffs"][round_code] = []
            last_post_season = g.season
        if int(g.game_pk) not in features.index:
            continue
        f = features.loc[g.game_pk].to_dict()
        state = _round_state(g, ctx, f, bool(is_post))
        for strategy in runnable:
            if not strategy.applies_to(g):
                continue
            decision = strategy.decide(g, f, ctx)
            decision = special_rules(strategy.sid, g, f, ctx, decision)
            if decision is None:
                continue
            selected_p = float(decision["p_model"])
            prediction_id = _prediction_id(run_id, strategy, int(g.game_pk))
            predictions.append({
                "prediction_id": prediction_id,
                "strategy_version_id": f"{strategy.sid}_{strategy.version}",
                "game_pk": int(g.game_pk), "environment": strategy.env,
                "round_code": None if pd.isna(getattr(g, "round_code", np.nan)) else g.round_code,
                "decision_time": str(g.start_ts), "data_cutoff_time": str(g.start_ts),
                "selection": decision["selection"], "model_probability": selected_p,
                "fair_price": selected_p, "required_price": decision.get("required_price"),
                "edge": None, "feature_snapshot_hash": db.stable_hash({"game_pk": int(g.game_pk), "features": f}),
                "source_observation_ids": source_observations, "availability_status": "SOURCE_BACKED",
                "result": None, "created_at": db.utcnow(),
            })
            result = _outcome(g, decision, strategy.market)
            predictions[-1]["result"] = result
            quote = _market_quote(f, decision, g, verified_source_ids, verified_observation_ids)
            has_result = result in {"W", "L", "P"}
            if quote is not None:
                from ..config import am_to_prob, devig_two
                if strategy.market == "ML":
                    tier = decision.get("price_tier") or "open"
                    if tier == "close":
                        hp, ap = am_to_prob(f.get("market_close_home_odds")), am_to_prob(f.get("market_close_away_odds"))
                    else:
                        hp, ap = am_to_prob(f.get("home_odds")), am_to_prob(f.get("away_odds"))
                    hp, ap = devig_two(hp, ap)
                    market_p = hp if decision["selection"] == "HOME" else ap
                    edge = selected_p - market_p if pd.notna(market_p) else None
                else:
                    market_p = None
                    edge = None
                decision["edge"] = edge
                if edge is not None and edge < strategy.min_edge:
                    counts["skipped"] += 1
                    continue
                stake = kelly_stake(bankrolls[(strategy.sid, strategy.env)], selected_p, quote["american"])
                if stake <= 0:
                    counts["skipped"] += 1
                    continue
                status = "SETTLED" if has_result else "OPEN"
                pnl = american_pnl(stake, quote["american"], result) if status == "SETTLED" and result else None
                # Closing-line value: entry vs close for the SAME side, only
                # when the entry was an earlier tier and a verified close exists.
                closing_price = None
                clv = None
                close_american = quote.get("close_american")
                if (quote.get("tier") != "close" and pd.notna(close_american)
                        and f.get("market_quote_verified")):
                    from ..config import am_to_prob as _am2p
                    from .evaluation import clv_probability
                    closing_price = float(close_american)
                    clv = clv_probability(float(quote["american"]), closing_price)
                if pnl is not None:
                    bankrolls[(strategy.sid, strategy.env)] += pnl
                    balances[(strategy.sid, strategy.env)].append((str(g.game_date), bankrolls[(strategy.sid, strategy.env)]))
                    counts["settled"] += 1
                else:
                    counts["open"] += 1
                bets.append(_bet_row(g, strategy, decision, stake, status, result, pnl,
                                     market_price=quote["american"], quote=quote, run_id=run_id,
                                     closing_price=closing_price, clv=clv))
            elif has_result:
                # A result can score model skill, but there is no bet or PnL.
                counts["eval"] += 1
                bets.append(_bet_row(g, strategy, decision, 0.0, "EVAL", result, None,
                                     run_id=run_id))
            else:
                counts["proposed"] += 1
                bets.append(_bet_row(g, strategy, decision, 0.0, "PROPOSED", None, None,
                                     run_id=run_id))
            if has_result and strategy.market in {"ML", "F5_ML"}:
                # y must be the outcome of the SELECTED side so it pairs with
                # p_selection: y=1 iff the model's own pick won.  (An earlier
                # build stored the home-win indicator here, which silently
                # inverted the label for every AWAY pick.)
                y = 1 if result == "W" else 0
                metrics[(strategy.sid, strategy.env)].append((selected_p, y))
        # Every model saw this game before the state update.  Update the series
        # state after all decisions, and only with a verified result.
        _update_series(g, state)
        if _has_score(g):
            _update_online_coefs(g, f, ctx, bool(is_post))
        if is_post and _has_score(g) and g.round_code in ROUNDS:
            p_elo = f.get("p_elo")
            if isinstance(p_elo, (float, int)) and math.isfinite(float(p_elo)):
                ctx["round_diffs"][g.round_code].append(int(g.home_score > g.away_score) - float(p_elo))

    _append_run_outputs(run_id, strategies, runnable, bets, predictions, balances, metrics, counts, bankrolls)
    with db.db() as conn:
        conn.execute("UPDATE backtest_runs SET finished_at=?,status=? WHERE run_id=?",
                     (db.utcnow(), "COMPLETED", run_id))
    db.audit("backtest:completed", db.jdump({"run_id": run_id, **counts}),
             entity_type="backtest_run", entity_id=run_id)
    return {"run_id": run_id, **{f"{k}_bets": v for k, v in counts.items()},
            "round_intercepts": {k: round(v, 6) for k, v in ctx["round_intercepts"].items()},
            "strategies": len(runnable)}


def _bet_row(g, strategy: Strategy, decision: dict[str, Any], stake: float,
             status: str, result: str | None, pnl: float | None,
             market_price: float | None = None, quote: dict[str, Any] | None = None,
             run_id: str | None = None,
             closing_price: float | None = None, clv: float | None = None) -> dict[str, Any]:
    return {
        "run_id": run_id, "prediction_id": _prediction_id(run_id or "run", strategy, int(g.game_pk)),
        "game_pk": int(g.game_pk), "strategy_id": strategy.sid, "env": strategy.env,
        "season": int(g.season), "round_code": None if pd.isna(getattr(g, "round_code", np.nan)) else g.round_code,
        "market": strategy.market, "selection": decision["selection"],
        "model_prob": decision["p_model"], "fair_price": decision["fair_price"],
        "required_price": decision.get("required_price"),
        "market_price": market_price, "edge": decision.get("edge"), "stake": stake,
        "made_at": db.utcnow(), "status": status, "result": result, "pnl": pnl,
        "closing_price": (closing_price if closing_price is not None
                          else (quote["american"] if quote and quote.get("closing") else None)),
        "clv": clv, "series_state": getattr(g, "series_key", None),
        "synthetic_pnl": None, "synthetic": 0,
        "verification_status": "VERIFIED_PRICE" if quote else "NO_MARKET_PRICE",
        "quote_source_id": quote.get("source_id") if quote else None,
        "quote_source_url": quote.get("source_url") if quote else None,
        "quote_source_observation_id": quote.get("source_observation_id") if quote else None,
        "quote_observed_at": quote.get("observed_at") if quote else None,
        "quote_available_at": quote.get("available_at") if quote else None,
        "quote_price_american": quote.get("american") if quote else None,
        "price_tier": (decision.get("price_tier") or "open") if quote else None,
    }


def _append_run_outputs(run_id, all_strategies, runnable, bets, predictions,
                        balances, metrics, counts, bankrolls) -> None:
    db.init_db()
    with db.db() as conn:
        for strategy in all_strategies:
            conn.execute(
                "INSERT OR IGNORE INTO strategies (strategy_id,name,env,model,market,hypothesis,status,created_at,notes) "
                "VALUES (?,?,?,?,?,?,?,?,?)",
                (strategy.sid, strategy.name, strategy.env, strategy.model, strategy.market,
                 strategy.hypothesis, strategy.status, db.utcnow(), strategy.notes),
            )
        for row in predictions:
            conn.execute(
                "INSERT OR IGNORE INTO predictions "
                "(prediction_id,strategy_version_id,game_pk,environment,round_code,decision_time,data_cutoff_time,"
                "selection,model_probability,fair_price,required_price,edge,feature_snapshot_hash,source_observation_ids,"
                "availability_status,result,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                tuple(row[c] for c in ("prediction_id", "strategy_version_id", "game_pk", "environment", "round_code",
                                      "decision_time", "data_cutoff_time", "selection", "model_probability", "fair_price",
                                      "required_price", "edge", "feature_snapshot_hash", "source_observation_ids",
                                      "availability_status", "result", "created_at")),
            )
        from .ledger import append_backtest_event
        for row in bets:
            cur = conn.execute(
                "INSERT INTO bets (game_pk,strategy_id,env,season,round_code,market,selection,model_prob,fair_price,"
                "market_price,edge,stake,made_at,status,result,pnl,closing_price,clv,series_state,synthetic_pnl,synthetic,"
                "run_id,prediction_id,verification_status,price_tier,required_price,quote_source_id,quote_source_url,"
                "quote_source_observation_id,quote_observed_at,quote_available_at,quote_price_american) "
                "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                tuple(row.get(c) for c in ("game_pk", "strategy_id", "env", "season", "round_code", "market", "selection",
                                      "model_prob", "fair_price", "market_price", "edge", "stake", "made_at", "status",
                                      "result", "pnl", "closing_price", "clv", "series_state", "synthetic_pnl", "synthetic",
                                      "run_id", "prediction_id", "verification_status", "price_tier", "required_price",
                                      "quote_source_id", "quote_source_url", "quote_source_observation_id",
                                      "quote_observed_at", "quote_available_at", "quote_price_american")),
            )
            if row["verification_status"] == "VERIFIED_PRICE" and row["status"] in {"OPEN", "SETTLED"}:
                bet_id = int(cur.lastrowid)
                append_backtest_event(conn, "BACKTEST_SETTLED" if row["status"] == "SETTLED" else "BACKTEST_OPEN", {
                    "bet_id": bet_id,
                    "strategy_version_id": f"{row['strategy_id']}_v1",
                    "game_pk": row["game_pk"], "environment": row["env"],
                    "round_code": row["round_code"], "market": row["market"],
                    "selection": row["selection"], "source_id": row.get("quote_source_id"),
                    "source_url": row.get("quote_source_url"),
                    "source_observation_id": row.get("quote_source_observation_id"),
                    "observed_at": row.get("quote_observed_at"),
                    "availability_at": row.get("quote_available_at"),
                    "price_american": row.get("quote_price_american"),
                    "price_decimal": _american_to_decimal(row["quote_price_american"]),
                    "implied_probability": am_to_prob(row["quote_price_american"]),
                    "model_probability": row["model_prob"],
                    "fair_price": row["fair_price"], "required_price": row.get("required_price"),
                    "edge": row["edge"], "stake": row["stake"],
                    "execution_status": "BACKTEST_OBSERVED_QUOTE",
                    "fill_quantity": row["stake"], "closing_price": row["closing_price"],
                    "result": row["result"], "settlement": row["result"], "pnl": row["pnl"],
                    "roi": (row["pnl"] / row["stake"] if row["pnl"] is not None and row["stake"] else None),
                    "verification_status": "VERIFIED",
                    "payload_json": db.jdump({"run_id": run_id, "prediction_id": row["prediction_id"]}),
                })
        for (strategy_id, env), points in metrics.items():
            if not points:
                continue
            p, y = zip(*points)
            from .evaluation import brier_score, log_loss
            conn.execute(
                "INSERT OR REPLACE INTO calibration (strategy_id,env,n_games,brier,log_loss,updated_at) VALUES (?,?,?,?,?,?)",
                (strategy_id, env, len(points), brier_score(p, y), log_loss(p, y), db.utcnow()),
            )
        # Bankroll is a derived run snapshot; unlike immutable_ledger it is
        # never used as the historical source of wager facts.
        seq = 0
        for (strategy_id, env), curve in balances.items():
            peak = STARTING_BANKROLL
            for date, balance in curve:
                peak = max(peak, balance)
                dd = (balance - peak) / peak if peak else 0.0
                conn.execute(
                    "INSERT OR IGNORE INTO bankroll (strategy_id,env,seq,game_date,balance,roi,max_dd) VALUES (?,?,?,?,?,?,?)",
                    (strategy_id, env, seq, date, balance, (balance - STARTING_BANKROLL) / STARTING_BANKROLL, dd),
                )
                seq += 1


def strategy_stats(run_id: str | None = None) -> pd.DataFrame:
    """Separate real-price PnL from unpriced evaluation outcomes."""
    db.init_db()
    sql = "SELECT * FROM bets" + (" WHERE run_id=?" if run_id else "")
    bets = db.query_df(sql, (run_id,) if run_id else ())
    if bets.empty:
        return pd.DataFrame(columns=["strategy_id", "env", "bets", "eval_picks", "settled", "pnl", "roi", "win_pct"])
    rows = []
    for (sid, env), group in bets.groupby(["strategy_id", "env"]):
        scored = group[group.result.isin(["W", "L", "P"])]
        traded = scored[(group.loc[scored.index, "verification_status"] == "VERIFIED_PRICE") & (scored.stake > 0)]
        wins, losses = (scored.result == "W").sum(), (scored.result == "L").sum()
        stake = float(traded.stake.fillna(0).sum())
        pnl = float(traded.pnl.fillna(0).sum()) if stake else None
        rows.append({"strategy_id": sid, "env": env, "bets": len(group),
                     "settled": int((group.status == "SETTLED").sum()),
                     "eval_picks": int((group.status == "EVAL").sum()),
                     "open": int((group.status == "OPEN").sum()),
                     "proposed": int((group.status == "PROPOSED").sum()),
                     "wins": int(wins), "losses": int(losses),
                     "win_pct": float(wins / (wins + losses)) if wins + losses else None,
                     "pnl": pnl, "stake_sum": stake, "roi": pnl / stake if stake else None})
    return pd.DataFrame(rows)


def combined_view(run_id: str | None = None) -> pd.DataFrame:
    stats = strategy_stats(run_id)
    if stats.empty:
        return stats
    rows = []
    for sid, group in stats.groupby("strategy_id"):
        reg = group[group.env == "REG"]
        post = group[group.env.isin(["POST", "WC", "DS", "LCS", "WS"])]
        reg_stake = float(reg.stake_sum.sum())
        post_stake = float(post.stake_sum.sum())
        reg_pnl = float(reg.pnl.dropna().sum()) if reg_stake else None
        post_pnl = float(post.pnl.dropna().sum()) if post_stake else None
        rows.append({"strategy_id": sid, "bets": int(group.bets.sum()),
                     "reg_bets": int(reg.bets.sum()), "reg_pnl": reg_pnl,
                     "reg_roi": (float(reg_pnl / reg_stake) if reg_stake and reg_pnl is not None else None),
                     "post_bets": int(post.bets.sum()), "post_eval_picks": int(post.eval_picks.sum()),
                     "post_pnl": post_pnl,
                     "post_rounds": sorted(post.env.unique().tolist())})
    return pd.DataFrame(rows)


if __name__ == "__main__":
    print(run_backtest())
